### ISSUE TITLE
Python or Swift?

### ISSUE THREAD

**Issue by alicerunsonfedora** [damienmsdevs/octoregister#1]
When we first started the reboot of developers' club, we wanted to go for a programming language of the future: Swift. However, there's also another easy-to-learn programming language that is much more mature and versatile than Swift: Python.

Let's use GitHub issues to talk about this and see if we still want to go with Swift or if we want to switch to Python.

**Comment by kotchet** [comment]
Swift, of course, if this is the language of the future. I would be less interested in switching to Python, since, while it is widely used in controlling hardware devices, e.g. Raspberry Pi, it is slower (due to interactive nature), in overall, compared to C or C++. I would be much more interested in a new language, if it uses a concept and a structure, similar to C and C++.

**Comment by alicerunsonfedora** [comment]
This is indeed a great point to make about Python; it's something I haven't really considered. Then again, I have only a little knowledge in Python and have more knowledge in Swift. As it stands, it could go one of three ways:

1. Keep using Swift and not consider Python at all.
2. Switch to Python and abandon Swift entirely.
3. Take a "both-and" approach and teach the two languages, each getting a dedicated quarter. 

I heavily support Swift and prefer it, but I also want to consider the future in addition to possible integration with the robotics club, unless the future entails that these two clubs go in two entirely separate directions. Having experience in Swift and Python could prove useful if we can successfully create a program for the roboRIO with it via RobotPy. _However, this is still ultimately up to the members **and** mentors of the club as to not only the integration of robotics but the language of choice as well._

**Comment by Mcasem** [comment]
Python only

**Comment by MaukaDragon1** [comment]
I am **COMPLETELY** new to the entire programming party. I just wish to learn the world of programming and to learn the one with the most benefits I can reap.... so why not both?

**Comment by brown96701** [comment]
My vote is with the "both-and" approach to teach both coding languages. I believe we should be prepared to go in any direction, and expand our horizons as best as possible. If Python and Swift can be studied, then great! If it's absolutely an either-or thing, I will be fine with either-or.

**Comment by Adam0902** [comment]
I think both sound very nice but I wish to make a website so I am heading toward swift.

**Comment by alicerunsonfedora** [comment]
Marking off as both-and

**Comment by alicerunsonfedora** [comment]
Pull request has come in, #3 , will close off issue
